binary_sensor:
  - platform: status
    id: system_status
    name: "Status"

button:
  - platform: restart
    id: restart_btn
    name: "Restart"

  - platform: factory_reset
    id: factory_reset_btn
    name: "Factory Reset"
    disabled_by_default: true

sensor:
  - platform: uptime
    type: timestamp
    name: "Uptime"

  - platform: wifi_signal
    id: wifi_signal_db
    name: "WiFi Signal"
