wifi:
  networks:
    - ssid: !secret wifi_ssid_302
      password: !secret wifi_password_302
    - ssid: !secret wifi_ssid_501
      password: !secret wifi_password_501

#   ap:
#     ssid: "ESPHome Fallback Hotspot"
#     password: !secret wifi_ap_password

#captive_portal:

improv_serial:
