esphome:
  name: bigbedroom-lights

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# esp8266:
#   board: nodemcuv2

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid_501
  password: !secret wifi_password_501
  ap:
    ssid: "bigbedroom-lights"
    password: !secret fallback_ap_password

captive_portal:

binary_sensor:
  - platform: gpio
    name: "A"
    pin:
      number: GPIO19
      mode:
        input: true
        # pullup: true
  - platform: gpio
    name: "B"
    pin:
      number: GPIO18
      mode:
        input: true
        # pullup: true
  - platform: gpio
    name: "C"
    pin:
      number: GPIO17
      mode:
        input: true
        # pullup: true
  - platform: gpio
    name: "D"
    pin:
      number: GPIO16
      # inverted: true
      mode:
        input: true
        # pullup: true

# # ESP8266
# binary_sensor:
#   - platform: gpio
#     name: "A"
#     pin:
#       number: D1
#       mode:
#         input: true
#   - platform: gpio
#     name: "B"
#     pin:
#       number: D2
#       mode:
#         input: true
#   - platform: gpio
#     name: "C"
#     pin:
#       number: D5
#       mode:
#         input: true
#   - platform: gpio
#     name: "D"
#     pin:
#       number: D6
#       mode:
#         input: true
