esphome:
  name: bigbedroom-lights

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

logger:

<<: !include .wifi.yaml
<<: !include .api.yaml
<<: !include .ota.yaml

binary_sensor:
  - platform: gpio
    name: "A"
    pin:
      number: GPIO19
      mode:
        input: true
        # pullup: true
  - platform: gpio
    name: "B"
    pin:
      number: GPIO18
      mode:
        input: true
        # pullup: true
  - platform: gpio
    name: "C"
    pin:
      number: GPIO17
      mode:
        input: true
        # pullup: true
  - platform: gpio
    name: "D"
    pin:
      number: GPIO16
      # inverted: true
      mode:
        input: true
        # pullup: true

time:
  - platform: homeassistant
    id: ha_time

sensor:
  - platform: uptime
    type: timestamp
    name: "Uptime"

  - platform: wifi_signal
    name: "WiFi Signal"
