esphome:
  name: ble-proxy-1051
  friendly_name: BLE Proxy 1051

esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf
    version: latest

logger:

<<: !include .wifi.yaml
<<: !include .api.yaml
<<: !include .ota.yaml

esp32_ble_tracker:

bluetooth_proxy:
  active: true

binary_sensor:
  # DIAGNOSTIC
  - platform: status
    id: system_status
    name: "Status"

time:
  # DIAGNOSTIC
  - platform: homeassistant
    id: ha_time

i2c:
  sda: 21
  scl: 22

sensor:
  - platform: dht
    pin: 16
    temperature:
      name: "DHT11 Temperature"
    humidity:
      name: "DHT11 Humidity"
    update_interval: 60s

  - platform: bh1750
    name: "BH1750 Illuminance"
    address: 0x23
    update_interval: 5s

  # DIAGNOSTIC
  - platform: uptime
    type: timestamp
    name: "Uptime"

  # DIAGNOSTIC
  - platform: wifi_signal
    name: "WiFi Signal"

  # # DIAGNOSTIC
  # - platform: internal_temperature
  #   name: "Internal Temperature"
