esphome:
  name: ble-proxy-s3
  friendly_name: BLE Proxy S3

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
  variant: esp32s3

logger:

<<: !include .wifi.yaml
<<: !include .api.yaml
<<: !include .ota.yaml

esp32_ble_tracker:

bluetooth_proxy:
  active: true

time:
  - platform: homeassistant
    id: ha_time

sensor:
  - platform: uptime
    type: timestamp
    name: Uptime
