esphome:
  name: ble-proxy-s3
  friendly_name: BLE Proxy S3

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
    version: latest
  variant: esp32s3

logger:

<<: !include .wifi.yaml
<<: !include .api.yaml
<<: !include .ota.yaml

esp32_ble_tracker:

bluetooth_proxy:
  active: true

binary_sensor:
  # DIAGNOSTIC
  - platform: status
    id: system_status
    name: "Status"

time:
  # DIAGNOSTIC
  - platform: homeassistant
    id: ha_time

sensor:
  # DIAGNOSTIC
  - platform: uptime
    type: timestamp
    name: "Uptime"

  # DIAGNOSTIC
  - platform: wifi_signal
    name: "WiFi Signal"

  # DIAGNOSTIC
  - platform: internal_temperature
    name: "Internal Temperature"

  - platform: sgp4x
    voc:
      id: voc
      name: "SGP4X VOC Index"
    nox:
      name: "SGP4X NOx Index"
    compensation:
      humidity_source: dht22_humi
      temperature_source: dht22_temp
    update_interval: 31s

  - platform: dht
    pin: 42
    temperature:
      name: "DHT22 Temperature"
      id: dht22_temp
    humidity:
      name: "DHT22 Humidity"
      id: dht22_humi
    update_interval: 29s

i2c:
  - sda: 47
    scl: 48
    scan: true
