substitutions:
  name: bluetooth-proxy
  board: nodemcu-32s

esphome:
  name: ${name}

esp32:
  board: ${board}
  framework:
    type: esp-idf

logger:

<<: !include .wifi.yaml
<<: !include .api.yaml
<<: !include .ota.yaml

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true
