substitutions:
  name: bluetooth-proxy
  board: nodemcu-32s
  framework_type: esp-idf

<<: !include BluetoothProxyBase.yaml

i2c:
  sda: 21
  scl: 22

sensor:
  - platform: dht
    pin: 16
    temperature:
      name: "DHT11 Temperature"
    humidity:
      name: "DHT11 Humidity"
    update_interval: 60s

  - platform: bh1750
    name: "BH1750 Illuminance"
    address: 0x23
    update_interval: 5s
