esphome:
  name: c6
  friendly_name: ESP32C6

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  framework:
    type: arduino
    version: latest

logger:

<<: !include .wifi.yaml
<<: !include .api.yaml
<<: !include .ota.yaml

binary_sensor:
  # DIAGNOSTIC
  - platform: status
    id: system_status
    name: "Status"

button:
  # DIAGNOSTIC
  - platform: restart
    name: "Restart"

  # DIAGNOSTIC
  - platform: factory_reset
    name: "Factory Reset"

time:
  # DIAGNOSTIC
  - platform: homeassistant
    id: ha_time

sensor:
  # DIAGNOSTIC
  - platform: uptime
    type: timestamp
    name: "Uptime"

  # DIAGNOSTIC
  - platform: wifi_signal
    name: "WiFi Signal"
    id: wifi_signal_db

  # DIAGNOSTIC
  - platform: internal_temperature
    id: esp_temperature
    name: "Internal Temperature"

esp32_ble_tracker:

bluetooth_proxy:
  active: true
