esphome:
  name: cabinet-fan

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

wifi:
  networks:
    - ssid: !secret wifi_ssid_302
      password: !secret wifi_password_302
    - ssid: !secret wifi_ssid_501
      password: !secret wifi_password_501
  ap:
    ssid: "cabinet-fan"
    password: !secret fallback_ap_password

captive_portal:

i2c:
  sda: 21
  scl: 22
  scan: true
  frequency: 50kHz
  id: bus_a

switch:
  - platform: gpio
    name: "Caibinet Fan"
    pin:
      number: GPIO25
      inverted: true

sensor:
  - platform: bmp085
    temperature:
      name: "Caibinet Temperature"
    pressure:
      name: "Caibinet Pressure"
    # address: 0x77
    update_interval: 60s
