# https://esphome.io/components/sensor/dallas.html

esphome:
  name: ds18b20

# esp32:
#   board: esp32-c3-devkitm-1
#   framework:
#     type: esp-idf
esp32:
  board: nodemcu-32s
  framework:
    type: arduino

logger:

<<: !include .wifi.yaml
<<: !include .api.yaml
<<: !include .ota.yaml

dallas:
  - pin: 3

# sensor:
#   - platform: dallas
#     address: 0x1C0000031EDD2A28
#     name: "Dallas Temperature"
