# https://esphome.io/components/sensor/dallas.html

esphome:
  name: ds18b20

# esp32:
#   board: esp32-c3-devkitm-1
#   framework:
#     type: esp-idf
esp32:
  board: nodemcu-32s
  framework:
    type: arduino

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

wifi:
  networks:
    - ssid: !secret wifi_ssid_302
      password: !secret wifi_password_302
    - ssid: !secret wifi_ssid_501
      password: !secret wifi_password_501
  ap:
    ssid: "fallback-ap"
    password: !secret fallback_ap_password

captive_portal:

dallas:
  - pin: 3

# sensor:
#   - platform: dallas
#     address: 0x1C0000031EDD2A28
#     name: "Dallas Temperature"
