packages:
  esphome.voice-assistant: github://esphome/firmware/wake-word-voice-assistant/esp32-s3-box-3.yaml@main
esphome:
  name_add_mac_suffix: false

<<: !include .wifi.yaml
<<: !include .api.yaml
<<: !include .ota.yaml
