substitutions:
  name: esp32-s3-box-3-5ab568
  friendly_name: ESP32 S3 Box 3
packages:
  esphome.voice-assistant: github://esphome/firmware/voice-assistant/esp32-s3-box-3.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

<<: !include .wifi.yaml
<<: !include .api.yaml
<<: !include .ota.yaml
