binary_sensor:
  # 雷达传感器
  - platform: gpio
    pin:
      number: GPIO21
    name: "Presence detect"
    device_class: "occupancy"
    filters:
      - delayed_off: !lambda return id(radar_delayed_off).state * 1000;
    on_release:
      then:
        - if:
            condition:
              switch.is_on: screen_auto_off
            then:
              - light.turn_off: led
    on_press:
      then:
        - if:
            condition:
              switch.is_on: screen_auto_off
            then:
              - light.turn_on: led

number:
  # 存在传感器超时配置
  - platform: template
    name: "Presence duration"
    id: radar_delayed_off
    icon: mdi:account-clock
    optimistic: true
    restore_value: true
    initial_value: 60
    min_value: 0
    step: 5
    max_value: 300
    unit_of_measurement: s
    entity_category: config
    mode: box

switch:
  # 无人自动关闭屏幕
  - platform: template
    name: "Screen Auto Off"
    id: screen_auto_off
    icon: mdi:account-right-arrow
    optimistic: true
    entity_category: config
    restore_mode: RESTORE_DEFAULT_OFF
