esphome:
  name: esp32-s3-zero-ble-proxy
  friendly_name: ESP32-S3-Zero BLE Proxy

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
  flash_size: 4MB
  variant: esp32s3

logger:

<<: !include .wifi.yaml
<<: !include .api.yaml
<<: !include .ota.yaml

esp32_ble_tracker:
  # scan_parameters:
  #   interval: 1100ms
  #   window: 1100ms
  #   active: true

bluetooth_proxy:
  # active: true
