#substitutions:
#  allowed_characters: " !#%'()+,-./0123456789:;<>?@ABCDEFGHIJKLMNOPQRSTUVWYZ[]_abcdefghijklmnopqrstuvwxyz{|}°²³µ—、一上不个中为主乾了些亮人任低佔何作供依侧係個側偵充光入全关冇冷几切到制前動區卧厅厨及口另右吊后吗启吸呀咗哪唔問啟嗎嘅嘛器圍在场執場外多大始安定客室家密寵对將小少左已帘常幫幾库度庫廊廚廳开式後恆感態成我戲戶户房所扇手打执把拔换掉控插摄整斯新明是景暗更最會有未本模機檯櫃欄次正氏水沒没洗活派温測源溫漏潮激濕灯為無煙照熱燈燥物狀玄现現瓦用發的盞目着睡私空窗立笛管節簾籬紅線红罐置聚聲脚腦腳臥色节著行衣解設調請謝警设调走路車车运連遊運過道邊部都量鎖锁門閂閉開關门闭除隱離電震霧面音頂題顏颜風风食餅餵，。？"

packages:
  esphome.voice-assistant: github://esphome/firmware/wake-word-voice-assistant/esp32-s3-box-3.yaml@main
  basic: !include .basic.yaml
  battery: !include esp32-s3-box-3.battery.yaml
  radar: !include esp32-s3-box-3.radar.yaml
  diagnostics: !include esp32-s3-box-3.diagnostics.yaml

esphome:
  name_add_mac_suffix: false

api:
  on_client_connected:
    - logger.log:
        format: "Client %s connected to API with IP %s"
        args: ["client_info.c_str()", "client_address.c_str()"]

#font:
#  - id: !extend font_request
#    file:
#      type: gfonts
#      family: Figtree
#      weight: 300
#      italic: true
#  - id: !extend font_response
#    file:
#      type: gfonts
#      family: Figtree
#      weight: 300
#  - id: !extend font_timer
#    file:
#      type: gfonts
#      family: Figtree
#      weight: 300

i2c:
  # 触摸屏、麦克风
  - id: bus_a
    sda: GPIO08
    scl: GPIO18
    scan: false
#    sda_pullup_enabled: true
#    scl_pullup_enabled: true
    frequency: 100kHz
  # 雷达、AHT30温湿度传感器
  - id: bus_b
    sda: GPIO41
    scl: GPIO40
    scan: false
    sda_pullup_enabled: true
    scl_pullup_enabled: true
    frequency: 100kHz

sensor:
  # AHT30温湿度传感器
  - platform: aht10
    i2c_id: bus_b
    variant: AHT20
    address: 0x38
    temperature:
      name: "AHT30 Temperature"
    humidity:
      name: "AHT30 Humidity"
    update_interval: 17s
