esphome:
  name: gate01
  friendly_name: 楼道门

esp8266:
  board: esp01_1m

logger:

<<: !include .wifi.yaml
<<: !include .api.yaml
<<: !include .ota.yaml

switch:
  - platform: gpio
    pin: GPIO0
    id: pin_phone
  - platform: gpio
    pin: GPIO2
    id: pin_lock

binary_sensor:
  # DIAGNOSTIC
  - platform: status
    id: system_status
    name: "Status"

  - platform: template
    id: lock_state

lock:
  - platform: template
    name: None
    id: gate_lock
    optimistic: true
    lambda: |-
      if (id(lock_state).state) {
        return LOCK_STATE_UNLOCKED;
      } else {
        return LOCK_STATE_LOCKED;
      }
    unlock_action:
      - binary_sensor.template.publish:
          id: lock_state
          state: ON
      - switch.turn_on: pin_phone
      - delay: 600ms
      - switch.turn_on: pin_lock
      - delay: 250ms
      - switch.turn_off: pin_lock
      - delay: 1250ms
      - switch.turn_off: pin_phone
      - delay: 50ms
      - binary_sensor.template.publish:
          id: lock_state
          state: OFF
    lock_action:
      - switch.turn_off: pin_lock
      - switch.turn_off: pin_phone
      - binary_sensor.template.publish:
          id: lock_state
          state: OFF

time:
  # DIAGNOSTIC
  - platform: homeassistant
    id: ha_time

sensor:
  # DIAGNOSTIC
  - platform: uptime
    type: timestamp
    name: "Uptime"

  # DIAGNOSTIC
  - platform: wifi_signal
    name: "WiFi Signal"
