esphome:
  name: gate
  includes:
    - GateSwitch.h

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

logger:

<<: !include .wifi.yaml
<<: !include .api.yaml
<<: !include .ota.yaml

switch:
- platform: custom
  lambda: |-
    auto gate_switch = new GateSwitch();
    App.register_component(gate_switch);
    return {gate_switch};
  switches:
    name: "楼道门"
