esphome:
  name: gate01
  friendly_name: 楼道门
  includes:
    - GateSwitch.h

esp8266:
  board: esp01_1m

logger:

<<: !include .wifi.yaml
<<: !include .api.yaml
<<: !include .ota.yaml

switch:
- platform: custom
  lambda: |-
    auto gate_switch = new GateSwitch();
    App.register_component(gate_switch);
    return {gate_switch};
  switches:
    name: "楼道门"
