packages:
  basic: !include .basic.yaml
  diagnostics: !include .diagnostics.yaml


esphome:
  name: gate01
  friendly_name: 楼道门

esp8266:
  board: esp01_1m

binary_sensor:
  - platform: template
    id: lock_state

switch:
  - platform: gpio
    pin: GPIO0
    id: pin_phone
  - platform: gpio
    pin: GPIO2
    id: pin_lock

lock:
  - platform: template
    name: None
    id: gate_lock
    optimistic: true
    lambda: |-
      if (id(lock_state).state) {
        return LOCK_STATE_UNLOCKED;
      } else {
        return LOCK_STATE_LOCKED;
      }
    unlock_action:
      - binary_sensor.template.publish:
          id: lock_state
          state: ON
      - switch.turn_on: pin_phone
      - delay: 600ms
      - switch.turn_on: pin_lock
      - delay: 250ms
      - switch.turn_off: pin_lock
      - delay: 1250ms
      - switch.turn_off: pin_phone
      - delay: 50ms
      - binary_sensor.template.publish:
          id: lock_state
          state: OFF
    lock_action:
      - switch.turn_off: pin_lock
      - switch.turn_off: pin_phone
      - binary_sensor.template.publish:
          id: lock_state
          state: OFF
