# https://esphome.io/components/sensor/ina219
esphome:
  name: ina219
  friendly_name: INA219

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

logger:

<<: !include .wifi.yaml
<<: !include .api.yaml
<<: !include .ota.yaml

i2c:
  sda: 21
  scl: 22

binary_sensor:
  # DIAGNOSTIC
  - platform: status
    id: system_status
    name: "Status"

button:
  # DIAGNOSTIC
  - platform: restart
    name: "Restart"

  # DIAGNOSTIC
  - platform: factory_reset
    name: "Factory Reset"

sensor:
  # DIAGNOSTIC
  - platform: uptime
    type: timestamp
    name: "Uptime"

  # DIAGNOSTIC
  - platform: wifi_signal
    name: "WiFi Signal"

  # DIAGNOSTIC
  - platform: internal_temperature
    name: "Internal Temperature"

  - platform: ina219
    address: 0x40
    shunt_resistance: 0.1 ohm
    current:
      name: "INA219 Current"
    power:
      name: "INA219 Power"
    bus_voltage:
      name: "INA219 Bus Voltage"
    shunt_voltage:
      name: "INA219 Shunt Voltage"
    max_voltage: 4.2V
    max_current: 1.2A
    update_interval: 1s

time:
  # DIAGNOSTIC
  - platform: homeassistant
    id: ha_time
