# https://esphome.io/components/sensor/sfa30
esphome:
  name: sfa30
  friendly_name: SFA30

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: arduino
    version: latest

logger:

<<: !include .wifi.yaml
<<: !include .api.yaml
<<: !include .ota.yaml

binary_sensor:
  # DIAGNOSTIC
  - platform: status
    id: system_status
    name: "Status"

button:
  # DIAGNOSTIC
  - platform: restart
    name: "Restart"

  # DIAGNOSTIC
  - platform: factory_reset
    name: "Factory Reset"

time:
  # DIAGNOSTIC
  - platform: homeassistant
    id: ha_time

i2c:
  sda: GPIO5
  scl: GPIO6

sensor:
  # DIAGNOSTIC
  - platform: uptime
    type: timestamp
    name: "Uptime"

  # DIAGNOSTIC
  - platform: wifi_signal
    name: "WiFi Signal"
    id: wifi_signal_db

  # DIAGNOSTIC
  - platform: internal_temperature
    id: esp_temperature
    name: "Internal Temperature"

  - platform: sfa30
    formaldehyde:
      name: "Formaldehyde"
      device_class: volatile_organic_compounds_parts
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 15s

esp32_ble_tracker:

bluetooth_proxy:
  active: true
