# https://esphome.io/components/display/ssd1306.html#ssd1306-spi

esphome:
  name: oled

# esp32:
#   board: esp32-c3-devkitm-1
#   framework:
#     type: esp-idf
esp32:
  board: nodemcu-32s
  framework:
    type: arduino

logger:

<<: !include .wifi.yaml
<<: !include .api.yaml
<<: !include .ota.yaml

font:
  - file: "BAUHS93.ttf"
    id: BAUHS93
    size: 16

spi:
  clk_pin: 18
  mosi_pin: 23

display:
  - platform: ssd1306_spi
    model: "SSD1306 128x64"
    cs_pin: 16
    dc_pin: 17
    reset_pin: 13
    lambda: |-
      it.print(0, 0, id(BAUHS93), "Hello World!");
      it.print(0, 16, id(BAUHS93), "Hello World!");
      it.print(0, 32, id(BAUHS93), "Hello World!");
      it.print(0, 48, id(BAUHS93), "Hello World!");
