# https://esphome.io/components/sensor/bh1750.html

esphome:
  name: bh1750

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

logger:

<<: !include .wifi.yaml
<<: !include .api.yaml
<<: !include .ota.yaml

i2c:
  sda: 21
  scl: 22

sensor:
  - platform: bh1750
    name: "BH1750 Illuminance"
    address: 0x23
    update_interval: 5s
