esphome:
  name: esp32-cam
  friendly_name: ESP32-CAM

esp32:
  board: esp32dev
  framework:
    type: arduino
    version: latest

logger:

<<: !include .wifi.yaml
<<: !include .api.yaml
<<: !include .ota.yaml

esp32_camera:
  name: ESP32-CAM
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: 800x600

output:
  - platform: ledc
    pin: GPIO4
    channel: 2 # channel 1 is used for esp32_camera
    id: led

light:
  - platform: monochromatic
    output: led
    name: Flash Light
    icon: mdi:spotlight

binary_sensor:
  # DIAGNOSTIC
  - platform: status
    id: system_status
    name: "Status"

time:
  # DIAGNOSTIC
  - platform: homeassistant
    id: ha_time

sensor:
  # DIAGNOSTIC
  - platform: uptime
    type: timestamp
    name: "Uptime"

  # DIAGNOSTIC
  - platform: wifi_signal
    name: "WiFi Signal"

  # # DIAGNOSTIC
  # - platform: internal_temperature
  #   name: "Internal Temperature"
