# https://esphome.io/components/display/ssd1306.html
# https://esphome.io/components/rtttl

esphome:
  name: nxez-cube
  friendly_name: NXEZ Cube

esp8266:
  board: d1_mini

logger:

<<: !include .wifi.yaml
<<: !include .api.yaml
<<: !include .ota.yaml

binary_sensor:
  # DIAGNOSTIC
  - platform: status
    id: system_status
    name: "Status"

time:
  # DIAGNOSTIC
  - platform: homeassistant
    id: ha_time

sensor:
  # DIAGNOSTIC
  - platform: uptime
    type: timestamp
    name: "Uptime"

  # DIAGNOSTIC
  - platform: wifi_signal
    name: "WiFi Signal"

output:
  - platform: esp8266_pwm
    pin: GPIO12
    frequency: 1000 Hz
    id: rtttl_out

rtttl:
  output: rtttl_out
  id: my_rtttl
  gain: 60%
  on_finished_playback:
    - logger.log: 'Song ended!'

button:
  - platform: template
    name: "Play Mario"
    on_press:
      then:
        - rtttl.play: "mario:d=4,o=5,b=100:16e6,16e6,32p,8e6,16c6,8e6,8g6,8p,8g,8p,8c6,16p,8g,16p,8e,16p,8a,8b,16a#,8a,16g.,16e6,16g6,8a6,16f6,8g6,8e6,16c6,16d6,8b,16p,8c6,16p,8g,16p,8e,16p,8a,8b,16a#,8a,16g.,16e6,16g6,8a6,16f6,8g6,8e6,16c6,16d6,8b,8p,16g6,16f#6,16f6,16d#6,16p,16e6,16p,16g#,16a,16c6,16p,16a,16c6,16d6,8p,16g6,16f#6,16f6,16d#6,16p,16e6,16p,16c7,16p,16c7,16c7,p,16g6,16f#6,16f6,16d#6,16p,16e6,16p,16g#,16a,16c6,16p,16a,16c6,16d6,8p,16d#6,8p,16d6,8p,16c6"

i2c:
  sda: D2
  scl: D1

font:
  - file: "gfonts://Roboto"
    id: roboto_12
    size: 12

text_sensor:
  - platform: homeassistant
    id: rpi4_temp
    entity_id: sensor.raspberry_pi_4b_temperature
  - platform: homeassistant
    id: rpi4_cpu
    entity_id: sensor.raspberry_pi_4b_cpu_usage
  - platform: homeassistant
    id: rpi4_mem
    entity_id: sensor.raspberry_pi_4b_memory_use
  - platform: homeassistant
    id: rpi4_load_1m
    entity_id: sensor.raspberry_pi_4b_load_1m
  - platform: homeassistant
    id: rpi4_load_5m
    entity_id: sensor.raspberry_pi_4b_load_5m
  - platform: homeassistant
    id: rpi4_load_15m
    entity_id: sensor.raspberry_pi_4b_load_15m
  - platform: homeassistant
    id: rpi4_upload
    entity_id: sensor.raspberry_pi_4b_network_upload
  - platform: homeassistant
    id: rpi4_download
    entity_id: sensor.raspberry_pi_4b_network_download

display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    lambda: |-
      it.print(0, 2, id(roboto_12), "Raspberry Pi 4B");
      it.printf(128, 2, id(roboto_12), TextAlign::TOP_RIGHT, "%s°C", id(rpi4_temp).state.c_str());
      it.printf(0, 18, id(roboto_12), "CPU: %s%", id(rpi4_cpu).state.c_str());
      it.printf(128, 18, id(roboto_12), TextAlign::TOP_RIGHT, "MEM: %s%", id(rpi4_mem).state.c_str());
      it.printf(0, 34, id(roboto_12), "Load: %s %s %s", id(rpi4_load_1m).state.c_str(), id(rpi4_load_5m).state.c_str(), id(rpi4_load_15m).state.c_str());
      it.printf(0, 50, id(roboto_12), "U:%sKiB/s", id(rpi4_upload).state.c_str());
      it.printf(128, 50, id(roboto_12), TextAlign::TOP_RIGHT, "D:%sKiB/s", id(rpi4_download).state.c_str());
